### ISSUE TITLE
Text Overflow with Typewriter Effect

### ISSUE THREAD

**Issue by lukemccrea** [GoodMorninTech/GoodMorningTech#56]
The typewriter effect on the home page overflows it's container when it has a long phrase and goes behind the subscribe form. The best way to fix this would probably be to increase the set height of that element or set it to auto.

**Comment by MaheshTheDeveloper** [comment]
I'll work on it...

**Comment by ImmaHarry** [comment]
Fixed on the development branch. Thank you for reporting!

**Comment by LevaniVashadze** [comment]
9bb1d9a fixed in this commit

**Comment by ImmaHarry** [comment]
Update: still needs work. Fixing this gave birth to another bug.

**Comment by TheMohit2003** [comment]
> Update: still needs work. Fixing this gave birth to another bug.
can you describe the bug ?

**Comment by ImmaHarry** [comment]
@TheMohit2003 
On medium-sized screens, the type-writer animation does not get wrapped correctly and starts overlapping the form.

P.S: I accidentally edited your comment, please ignore that!

**Comment by TheMohit2003** [comment]
I will work on it and update you soon

**Comment by ImmaHarry** [comment]
> I will work on it and update you soon

Okay! Thanks, also if you are not on our Discord Server, you should join it since communicating will be easier there. https://dsc.gg/goodmorningtech .

**Comment by ImmaHarry** [comment]
This has been fixed.
