### ISSUE TITLE
404 not  working correcting

### ISSUE THREAD

**Issue by electro199** [GoodMorninTech/GoodMorningTech#60]
![image](https://user-images.githubusercontent.com/109358640/215023279-9a157c73-25e3-41ad-a925-ec48f3ab9915.png)
it is not directing back me to home page

**Comment by OpenSourceSimon** [comment]
Hey thanks for taking a look! Should be fixed in development branch. https://dev.goodmorningtech.news

**Comment by ImmaHarry** [comment]
Yes, as suggested by Simon, this has already been resolved in the development branch. As indicated by the screenshot below:
![image](https://user-images.githubusercontent.com/62475932/215029537-6c3b4812-bedb-4a18-b7aa-326a1822c714.png)

Example: https://dev.goodmorningtech.news/testing123
